# Generated by Django 2.2.10 on 2020-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is test description and w ajshdkjasbdkjamassbcnansb asjkdhajksdh kjajbhfjksahf kjsadjfhjksdhfjk '),
            preserve_default=False,
        ),
    ]
