# Generated by Django 2.2.10 on 2020-04-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
