# Generated by Django 2.2.10 on 2020-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200424_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='index.jpg', upload_to=''),
        ),
    ]
